dataset_defaults = {
    'iwildcam': {
        'epochs': 15,
        'batch_size': 16,
        'eval_batch_size': 64,
        'optimiser': 'Adam',
        'optimiser_args': {
            'lr': 3e-5,
            'weight_decay': 0.0,
            'amsgrad': True,
            'betas': (0.9, 0.999),
        },
        'selection_metric': 'F1-macro_all',
        'print_loss_iters': 1000,
        'iter_num': 1000,
        'mix_alpha': 0.5,
        'c': 512,
        'h': 56,
        'w': 56,
    },
    'domainnet': {
        'epochs': 15,
        'batch_size': 18,
        'eval_batch_size': 256,
        'optimiser': 'Adam',
        'optimiser_args': {
            'lr': 3e-5,
            'weight_decay': 1e-6,
            'amsgrad': True,
            'betas': (0.9, 0.999),
        },
        'selection_metric': 'Average Pair acc',
        'print_loss_iters': 1000,
        'iter_num': 1000,
        'mix_alpha': 0.5,
        'c': 512,
        'h': 28,
        'w': 28,
    },
    'officehome': {
        'epochs': 15,
        'batch_size': 18,
        'eval_batch_size': 256,
        'optimiser': 'Adam',
        'optimiser_args': {
            'lr': 3e-5,
            'weight_decay': 1e-6,
            'amsgrad': True,
            'betas': (0.9, 0.999),
        },
        'selection_metric': 'Average Pair acc',
        'print_loss_iters': 100,
        'iter_num': 500,
        'mix_alpha': 0.5,
        'c': 512,
        'h': 28,
        'w': 28,
    },
    'PACS': {
        'epochs': 15,
        'batch_size': 18,
        'eval_batch_size': 256,
        'optimiser': 'Adam',
        'optimiser_args': {
            'lr': 1e-5,
            'weight_decay': 1e-6,
            'amsgrad': True,
            'betas': (0.9, 0.999),
        },
        'selection_metric': 'Average Pair acc',
        'print_loss_iters': 100,
        'iter_num': 500,
        'mix_alpha': 0.5,
        'c': 512,
        'h': 28,
        'w': 28,
    },
    'VLCS': {
        'epochs': 15,
        'batch_size': 18,
        'eval_batch_size': 256,
        'optimiser': 'Adam',
        'optimiser_args': {
            'lr': 1e-5,
            'weight_decay': 1e-6,
            'amsgrad': True,
            'betas': (0.9, 0.999),
        },
        'selection_metric': 'Average Pair acc',
        'print_loss_iters': 100,
        'iter_num': 200,
        'mix_alpha': 0.2,
        'c': 512,
        'h': 28,
        'w': 28,
    },
    'terraincognita': {
        'epochs': 15,
        'batch_size': 18,
        'eval_batch_size': 256,
        'optimiser': 'Adam',
        'optimiser_args': {
            'lr': 3e-5,
            'weight_decay': 0.0,
            'amsgrad': True,
            'betas': (0.9, 0.999),
        },
        'selection_metric': 'F1-macro',
        'print_loss_iters': 500,
        'iter_num': 1000,
        'mix_alpha': 0.5,
        'c': 512,
        'h': 28,
        'w': 28,
    }
}